In [15]:
import pandas as pd
import numpy as np
import re

In [16]:
df = pd.read_csv("/content/drive/MyDrive/campus x /Capstone Project /gurgaon_properties.csv")

In [17]:
df.sample(5)

,property_name,society,price,price_per_sqft,area,property_type,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
3319,3 BHK Flat in Sohna,signature global park,0.90,8036.0,1120.00000,flat,Built Up area: 1120 (104.05 sq.m.),3.0,2.0,0,not available,"Sohna Sector 36, Sohna, Gurgaon, Haryana",2.0,NaN,2024-03-01 00:00:00,"['Sector 55-56 metro', 'Global city centre', '...",Best in class property available at sector 36 ...,NaN,NaN,"['Green Area5 out of 5', 'Amenities5 out of 5'..."
2502,6 Bedroom House for sale in DLF Phase 1,dlf city plots,26.00,57206.0,4544.97780,house,Plot area 505(422.24 sq.m.),6.0,7.0,3+,"Pooja Room,Study Room,Servant Room,Others","0000, DLF Phase 1, Gurgaon, Haryana",2.0,North-East,0 to 1 Year Old,"['Phase 2 Metro Station', 'Grand Mall', 'Jacar...",505 sq.Y 6 bhk luxury villa \nIn dlf phase 1\n...,"['12 Fan', '1 Exhaust Fan', '6 Geyser', '1 Sto...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
1377,2 BHK Flat in Sohna,gls arawali homes,0.26,4513.0,576.00000,flat,Carpet area: 576 (53.51 sq.m.),2.0,2.0,2,not available,"Sohna, Gurgaon, Haryana",4.0,NaN,1 to 5 Year Old,"['Huda City Centre', 'Golf Course Road', 'Delh...",Residential apartment for sell.Located on 4th ...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction4 out of..."
2051,2 BHK Flat in Sector 79 Gurgaon,supertech araville,0.71,6061.0,1171.00000,flat,Super Built up area 1295(120.31 sq.m.)Carpet a...,2.0,2.0,3+,others,"E 1706, Sector 79 Gurgaon, Gurgaon, Haryana",17.0,North,0 to 1 Year Old,"['Petrol Pump Indian Oil', 'Petrol Pump', 'Rao...",This is your chance to own a 2 bhk residential...,"['2 Wardrobe', '2 Geyser', '1 Light', '2 AC', ...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1349,6 Bedroom House for sale in Sector 55 Gurgaon,NaN,5.60,20741.0,2699.96625,house,Plot area 300(250.84 sq.m.),6.0,4.0,3,Servant Room,"Sector 55 Gurgaon, Gurgaon, Haryana",3.0,East,10+ Year Old,"['Sector metro station', 'Sector metro station...",Luxurious villa for sale\nLocation - Sector 55...,"['10 Fan', '4 Geyser', '12 Light', '4 AC', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [18]:
df.insert(3, column = 'sector', value = df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon', '').str.strip().str.lower())

In [19]:
df.head(2)

,property_name,society,price,sector,price_per_sqft,area,property_type,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 67 Gurgaon,ireo victory valley,2.99,sector 67,11832.0,2527.0,flat,Super Built up area 2527(234.77 sq.m.)Built Up...,3.0,3.0,...,servant room,"702, Sector 67 Gurgaon, Gurgaon, Haryana",4.0,East,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",Note- We deal exclusively in the society ireo ...,"['3 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 St...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."
1,2 BHK Flat in Sohna,signature global park,0.58,sohna,7056.0,822.0,flat,Built Up area: 822 (76.37 sq.m.)Carpet area: 6...,2.0,2.0,...,not available,"Sohna Sector 36, Sohna, Gurgaon, Haryana",3.0,NaN,undefined,"['Sector 55-56 metro', 'Global city centre', '...",Best in class property available at sector 36 ...,NaN,NaN,"['Green Area5 out of 5', 'Construction5 out of..."

In [21]:
df['sector'].value_counts()

sohna                       164
sector 102                  113
sector 85                   110
sector 92                   105
sector 109                  103
                           ...
mahavir pura                  1
heera nagar                   1
anand garden, sector-105      1
shivji park colony            1
garauli kalan                 1
Name: sector, Length: 305, dtype: int64

In [22]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [30]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3].index

In [34]:
df = df[df['sector'].isin(a)]

In [35]:
df['sector'].value_counts()

sohna road           164
sector 102           113
sector 85            110
sector 92            105
sector 109           103
                    ...
bissar                 3
sector 27              3
a block sector 43      3
sector 17b             3
sector 17a             3
Name: sector, Length: 134, dtype: int64

In [36]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [38]:
df[df['sector'] == 'new']

,property_name,society,price,sector,price_per_sqft,area,property_type,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1268,4 BHK Flat in New Gurgaon,dlf 76,4.00,new,11428.0,3500.0,flat,Carpet area: 3500 (325.16 sq.m.),4.0,4.0,...,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,2027-06-01 00:00:00,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2661,2 BHK Flat in New Gurgaon,green court,0.38,new,5507.0,690.0,flat,Carpet area: 690 (64.1 sq.m.),2.0,2.0,...,not available,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2834,2 BHK Flat in New Gurgaon,takshila heights sector 37 c,0.67,new,5583.0,1200.0,flat,Super Built up area 1200(111.48 sq.m.),2.0,2.0,...,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN
3061,4 BHK Flat in New Gurgaon,sare homes,0.85,new,4786.0,1776.0,flat,Super Built up area 1776(165 sq.m.),4.0,4.0,...,not available,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN

In [41]:
df.loc[2834, 'sector'] = 'sector 37'
df.loc[3061,'sector'] = 'sector 92'
df.loc[2661,'sector'] = 'sector 90'
df.loc[1268,'sector'] = 'sector 76'

In [42]:
df[df['sector'] == 'new sector 2']

,property_name,society,price,sector,price_per_sqft,area,property_type,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
401,3 Bedroom House for sale in New Palam Vihar,NaN,1.00,new sector 2,8796.0,1136.880400,house,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3.0,2.0,...,Pooja Room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
464,2 BHK Flat in New Palam Vihar,ompee k s residency,1.60,new sector 2,26936.0,594.000000,flat,Carpet area: 66 (55.18 sq.m.),2.0,2.0,...,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
939,2 BHK Flat in New Palam Vihar,my home,0.22,new sector 2,4400.0,500.000000,flat,Carpet area: 500 (46.45 sq.m.),2.0,2.0,...,not available,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
2010,2 Bedroom House for sale in New Palam Vihar,my home,0.34,new sector 2,12592.0,270.012706,house,Plot area 270(25.08 sq.m.),2.0,2.0,...,Not Available,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2977,2 Bedroom House for sale in New Palam Vihar,NaN,NaN,new sector 2,8000.0,NaN,house,NaN,NaN,NaN,...,Not Available,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3810,2 BHK Flat in New Palam Vihar,my home,0.28,new sector 2,3166.0,884.000000,flat,Carpet area: 900 (83.61 sq.m.),2.0,1.0,...,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [46]:
df[df['sector'] == 'new sector 2'].index

Int64Index([401, 464, 939, 2010, 2977, 3810], dtype='int64')

In [48]:
df.loc[[401, 464, 939, 2010, 2977, 3810], 'sector'] = 'sector 110'

In [50]:
df.shape

(3925, 21)

In [52]:
df.duplicated().sum()

23

In [55]:
df.drop_duplicates(inplace = True)

In [56]:
df.duplicated().sum()

0

In [57]:
df.shape

(3902, 21)

In [58]:
df.head()

,property_name,society,price,sector,price_per_sqft,area,property_type,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 67 Gurgaon,ireo victory valley,2.99,sector 67,11832.0,2527.000,flat,Super Built up area 2527(234.77 sq.m.)Built Up...,3.0,3.0,...,servant room,"702, Sector 67 Gurgaon, Gurgaon, Haryana",4.0,East,1 to 5 Year Old,"['AIPL Joy Street Mall', 'Golf Course Extensio...",Note- We deal exclusively in the society ireo ...,"['3 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 St...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of..."
1,2 BHK Flat in Sohna,signature global park,0.58,sohna road,7056.0,822.000,flat,Built Up area: 822 (76.37 sq.m.)Carpet area: 6...,2.0,2.0,...,not available,"Sohna Sector 36, Sohna, Gurgaon, Haryana",3.0,NaN,undefined,"['Sector 55-56 metro', 'Global city centre', '...",Best in class property available at sector 36 ...,NaN,NaN,"['Green Area5 out of 5', 'Construction5 out of..."
2,2 BHK Flat in Sector 71 Gurgaon,chd avenue,0.95,sector 71,7917.0,1200.000,flat,Built Up area: 1200 (111.48 sq.m.),2.0,2.0,...,not available,"Sector 71, Sector 71 Gurgaon, Gurgaon, Haryana",5.0,South,undefined,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Best in class property available at sector 71 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction3 out of..."
3,3 BHK Flat in Sector 43 Gurgaon,ansal maple heights,1.50,sector 43,12658.0,1185.000,flat,Super Built up area 1400(130.06 sq.m.)Built Up...,3.0,3.0,...,store room,"7-03, Sector 43 Gurgaon, Gurgaon, Haryana",7.0,North-East,10+ Year Old,"['Huda city centre metro station', 'Iffco chow...","Ansal maple heights in sector 43, gurgaon is a...","['3 Wardrobe', '1 Water Purifier', '10 Fan', '...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of..."
4,5 Bedroom House for sale in Sector 15 Gurgaon,sector 15 part 2 rwa,10.00,sector 15,22222.0,4500.045,house,Plot area 502(419.74 sq.m.),5.0,5.0,...,Not Available,"Sector 15 Gurgaon, Gurgaon, Haryana",2.0,East,10+ Year Old,"['Hanuman Mandir', 'State bank of india ATM', ...","Gated community and near market,school and hig...",[],"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4.5 out of 5', 'Lifestyle4 out of..."

#Drop unnecessary columns

In [59]:
df.drop(columns = ['property_name', 'address', 'description', 'rating'], inplace = True)

In [60]:
df.sample(5)

,society,price,sector,price_per_sqft,area,property_type,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1540,corona optus,1.25,sector 37c,8928.0,1400.000000,flat,Super Built up area 1735(161.19 sq.m.)Carpet a...,3.0,3.0,3,study room,2.0,South-East,1 to 5 Year Old,"['The Esplanade Mall', 'Gurugram Road', 'Delhi...",NaN,"['Feng Shui / Vaastu Compliant', 'Security / F..."
3836,NaN,11.00,sector 28,33951.0,3239.963477,house,Plot area 360(301.01 sq.m.),13.0,13.0,3+,"Pooja Room,Study Room,Servant Room",3.0,East,1 to 5 Year Old,"['Dlf phase 1 metro station', 'Huda city centr...","['1 Water Purifier', '16 Fan', '1 Exhaust Fan'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1503,sunischit apartments,1.75,sector 54,7954.0,2200.000000,flat,Super Built up area 2200(204.39 sq.m.)Built Up...,3.0,3.0,3+,servant room,6.0,North-East,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...","['4 Fan', '1 Exhaust Fan', '3 Geyser', '24 Lig...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
1668,dlf the primus,2.20,sector 82a,10516.0,2092.000000,flat,Super Built up area 2092(194.35 sq.m.),3.0,3.0,3+,servant room,16.0,North-East,1 to 5 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...","['1 Water Purifier', '6 Fan', '1 Fridge', '1 E...","['Centrally Air Conditioned', 'Water purifier'..."
1827,unitech sunbreeze,0.75,sector 69,6849.0,1095.000000,flat,Super Built up area 1095(101.73 sq.m.),2.0,2.0,2,not available,4.0,NaN,By 2024,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",[],NaN

In [63]:
df.to_csv('gurgaon_properties_cleaned_v1.csv', index = False)